### ISSUE TITLE
Typescript doesn't recognize @turbopandarepo/ds

### ISSUE THREAD

**Issue by andrewdoro** [AdamQuadmon/turbopandarepo#1]
Currently auto-importing from @turbopandarepo/ds it's not working, I also have this error in my project. Any idea how to fix this?

**Comment by AdamQuadmon** [comment]
> Currently auto-importing from @turbopandarepo/ds it's not working, I also have this error in my project. Any idea how to fix this?

Sorry for the late reply, I didn't code during summer.
Now I did some big changes in the configs.
The ones related to the generated styled-system are these:

- added @turbopandarepo/ds to knip ignoreDependencies
- added @turbopandarepo/ds to allowModules in eslint n/no-extraneous-import rule
- added "node_modules/@turbopandarepo/ds" to apps/docs tsconfig.json

This stops typescript complains.

I have to check if the new `config.importMap` Panda options (https://github.com/chakra-ui/panda/pull/1422) can do this better.

**Comment by andrewdoro** [comment]
Fixed by this approach
https://github.com/astahmer/panda-monorepo-setup/blob/main/module-resolution/with-import-map/app/panda.config.ts
